Repository warewulf/warewulf, pull requests merged in 2023-09, with the labels that each got.

#853 fix SIGSEV if build host has no network
  CHANGELOG.md
  CONTRIBUTORS.md
  internal/pkg/config/root.go
Labels: bug

#903 Fix warewulfd for new contextual overlay names
  go.mod
  go.sum
  internal/pkg/overlay/config.go
  internal/pkg/overlay/config_test.go
  internal/pkg/overlay/overlay.go
  internal/pkg/overlay/overlay_test.go
  internal/pkg/warewulfd/provision.go
  internal/pkg/warewulfd/provision_test.go
  internal/pkg/warewulfd/util.go
  internal/pkg/warewulfd/util_test.go
Labels: bug

#900 Updated Makefile to account for vendor/ in dist
  Dockerfile
  Makefile
  Tools.mk
  Variables.mk
  userdocs/contributing/development-environment-vagrant.rst
  userdocs/quickstart/el8.rst
  userdocs/quickstart/el9.rst
  userdocs/quickstart/suse15.rst
  warewulf.spec.in
Labels: bug

#902 Update overlay edit with tempfile and mtime
  CHANGELOG.md
  internal/app/wwctl/overlay/edit/main.go
Labels: bug

#927 Update CHANGELOG for changes to overlay names
  CHANGELOG.md
Labels: documentation

#928 Update GitHub issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: project

#843 Update LICENSE.md for formatting and contributors
  LICENSE.md
Labels: project
