Repository warewulf/warewulf, pull requests merged in 2023-12, with the labels that each got.

#961 moved initialization of ConfigFile to New()
  internal/pkg/node/constructors.go
Labels: bug, refactor

#942 import symlinked /bin/sh
  CHANGELOG.md
  internal/pkg/util/util.go
Labels: bug

#1019 Add Debian quickstart
  userdocs/index.rst
  userdocs/quickstart/debian12.rst
Labels: documentation

#1010 Use distribution iPXE
  CHANGELOG.md
  Makefile
  README.md
  Variables.mk
  etc/warewulf.conf
  internal/pkg/config/buildconfig.go.in
  internal/pkg/config/tftp.go
  internal/pkg/configure/tftp.go
  ipxe-update.sh
  staticfiles/README-ipxe.md
  staticfiles/README.md
  staticfiles/arm64.efi
  staticfiles/x86_64.efi
  staticfiles/x86_64.kpxe
  warewulf.spec.in
Labels: enhancement

#1023 Fix relative iPXE paths
  internal/pkg/config/tftp.go
Labels: bug

#1017 Update 10-persistent-net.link.ww
  CHANGELOG.md
  docs/man/man5/defaults.conf.5
  internal/pkg/node/constructors.go
  overlays/wwinit/etc/systemd/network/10-persistent-net.link.ww
Labels: bug

#1026 Update iPXE build script
  CHANGELOG.md
  README.md
  ipxe-update.sh
  scripts/build-ipxe.sh
Labels: refactor

#1027 Suppress vendor errors in makefile
  Variables.mk
Labels: build
