Repository warewulf/warewulf, pull requests merged in 2023-10, with the labels that each got.

#945 Mark vendor target phony and update
  Makefile
  go.mod
Labels: build

#778 return the primary network interface for discoverd
  CHANGELOG.md
  internal/pkg/node/constructors.go
  internal/pkg/node/constuctors_test.go
Labels: bug

#955 added general testing framework
  CHANGELOG.md
  internal/app/wwctl/node/set/main_test.go
  internal/pkg/testenv/testenv.go
  internal/pkg/testenv/testenv_test.go
Labels: testing

#943 only write ipmi of IpmiWrite is true
  CHANGELOG.md
  overlays/wwinit/warewulf/init.d/50-ipmi
Labels: bug

#946 set MTU in different network confs
  CHANGELOG.md
  overlays/wwinit/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/wwinit/etc/network/interfaces.d/default.ww
  overlays/wwinit/etc/sysconfig/network-scripts/ifcfg.ww
  overlays/wwinit/etc/wicked/ifconfig/ifcfg.xml.ww
Labels: bug

#948 mtu can be set via command line
  CHANGELOG.md
  internal/app/wwctl/node/set/main_test.go
  internal/pkg/node/flags.go
Labels: bug

#950 no error if images for containers don't exist
  CHANGELOG.md
  internal/pkg/api/container/container.go
Labels: bug

#949 check if entry has real value in recursive getter
  CHANGELOG.md
  internal/app/wwctl/node/set/main_test.go
  internal/pkg/node/transformers.go
Labels: bug

#957 Updated the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: project

#958 Skip changelog enforcement for certain labels
  .github/workflows/changelog-enforcer.yml
Labels: project

#951 Refactor the release workflow
  .github/workflows/changelog-enforcer.yml
  .github/workflows/release.yml
  .github/workflows/releasebuild.yml
  CHANGELOG.md
  Makefile
  Variables.mk
  ci/mockbuild.sh
  warewulf.spec.in
Labels: build

#894 calling the overlay build functions direclty
  internal/pkg/overlay/overlay.go
  internal/pkg/overlay/overlay_test.go
  internal/pkg/warewulfd/provision.go
  internal/pkg/warewulfd/util.go
  internal/pkg/warewulfd/util_test.go
Labels: refactor
