Repository warewulf/warewulf, pull requests merged in 2023-02, with the labels that each got.

#639 use default not override for single network entry
  internal/pkg/node/constructors.go
  internal/pkg/node/methods.go
Labels: enhancement

#667 Correct header for overlay list -al
  CHANGELOG.md
  internal/app/wwctl/overlay/list/main.go
Labels: bug, 4.4.x

#692 Fix newline when printing AllNodes
  overlays/debug/warewulf/template-variables.md.ww
Labels: bug

#686 updated the documentation to match 4.4.0 features
  userdocs/conf.py
  userdocs/contents/configuration.rst
  userdocs/contents/containers.rst
  userdocs/contents/initialization.rst
  userdocs/contents/ipmi.rst
  userdocs/contents/nodeconfig.rst
  userdocs/contents/overlays.rst
  userdocs/contents/profiles.rst
  userdocs/contents/templating.rst
Labels: documentation, 4.4.x

#700 Capitalize Warewulf in userdocs where appropriate
  userdocs/contents/containers.rst
  userdocs/contributing/development-environment-kvm.rst
  userdocs/contributing/development-environment-vbox.rst
  userdocs/debian/debian.md
Labels: documentation

#705 Reflow all userdocs text
  userdocs/contents/background.rst
  userdocs/contents/configuration.rst
  userdocs/contents/containers.rst
  userdocs/contents/initialization.rst
  userdocs/contents/installation.rst
  userdocs/contents/introduction.rst
  userdocs/contents/ipmi.rst
  userdocs/contents/kernel.rst
  userdocs/contents/nodeconfig.rst
  userdocs/contents/overlays.rst
  userdocs/contents/profiles.rst
  userdocs/contents/provisioning.rst
  userdocs/contents/security.rst
  userdocs/contents/setup.rst
  userdocs/contents/stateless.rst
  userdocs/contents/templating.rst
  userdocs/contributing/contributing.rst
  userdocs/contributing/development-environment-vbox.rst
  userdocs/contributing/documentation.rst
  userdocs/index.rst
  userdocs/quickstart/el7.rst
  userdocs/quickstart/el8.rst
  userdocs/quickstart/suse15.rst
  userdocs/reference/glossary.rst
Labels: documentation

#706 Fix code-style dash formatting in userdocs
  userdocs/contents/ipmi.rst
Labels: documentation

#707 Console-style code-block and remove sudo
  userdocs/contents/containers.rst
  userdocs/contents/initialization.rst
  userdocs/contents/installation.rst
  userdocs/contents/ipmi.rst
  userdocs/contents/kernel.rst
  userdocs/contents/nodeconfig.rst
  userdocs/contents/overlays.rst
  userdocs/contents/profiles.rst
Labels: documentation

#708 Fix accidental userdocs italics
  userdocs/contents/containers.rst
  userdocs/contents/initialization.rst
  userdocs/contents/installation.rst
  userdocs/contents/ipmi.rst
  userdocs/contents/overlays.rst
  userdocs/contents/templating.rst
  userdocs/quickstart/el7.rst
Labels: documentation

#693 Emit canonical hostnames first
  CHANGELOG.md
  overlays/generic/etc/hosts.ww
  overlays/host/etc/hosts.ww
Labels: stake:ciq

#701 Initial dependabot configuration
  .github/dependabot.yml
Labels: ci/cd

#673 build host overlay only if requested
  internal/app/wwctl/overlay/build/main.go
Labels: bug, 4.4.x

#651 make ipxe binary source configurable
  internal/pkg/buildconfig/defaults.go
  internal/pkg/configure/tftp.go
  internal/pkg/overlay/datastructure.go
  internal/pkg/warewulfconf/constructors.go
  internal/pkg/warewulfconf/datastructure.go
  overlays/host/etc/dhcp/dhcpd.conf.ww
Labels: stake:suse

#683 make output less scary for new files
  internal/app/wwctl/overlay/edit/main.go
  internal/app/wwctl/overlay/edit/root.go
  internal/app/wwctl/overlay/imprt/root.go
Labels: bug, 4.4.x
