Repository warewulf/warewulf, pull requests merged in 2023-08, with the labels that each got.

#839 Refactor syncuids and fix GID chown
  CHANGELOG.md
  internal/pkg/api/container/container.go
  internal/pkg/container/syncuids.go
  internal/pkg/container/syncuids_test.go
Labels: bug, 4.4.x

#871 reboot also without systemd
  CHANGELOG.md
  overlays/wwinit/init
Labels: bug

#786 disk support for warewulf
  .github/workflows/test.yml
  CHANGELOG.md
  go.mod
  go.sum
  internal/app/wwctl/node/add/main.go
  internal/app/wwctl/node/add/main_test.go
  internal/app/wwctl/node/add/root.go
  internal/app/wwctl/node/edit/main.go
  internal/app/wwctl/node/list/main.go
  internal/app/wwctl/node/list/root.go
  internal/app/wwctl/node/set/main.go
  internal/app/wwctl/node/set/main_test.go
  internal/app/wwctl/node/set/root.go
  internal/app/wwctl/overlay/show/main.go
  internal/app/wwctl/profile/add/main.go
  internal/app/wwctl/profile/add/main_test.go
  internal/app/wwctl/profile/add/root.go
  internal/app/wwctl/profile/edit/main.go
  internal/app/wwctl/profile/list/main.go
  internal/app/wwctl/profile/list/root.go
  internal/app/wwctl/profile/set/main.go
  internal/app/wwctl/profile/set/root.go
  internal/pkg/api/node/list.go
  internal/pkg/api/node/methods.go
  internal/pkg/api/node/node.go
  internal/pkg/api/profile/list.go
  internal/pkg/api/profile/profile.go
  internal/pkg/api/routes/v1/routes.proto
  internal/pkg/api/routes/wwapiv1/routes.pb.go
  internal/pkg/configure/hostfile.go
  internal/pkg/node/constructors.go
  internal/pkg/node/datastructure.go
  internal/pkg/node/flags.go
  internal/pkg/node/ignition.go
  internal/pkg/node/list.go
  internal/pkg/node/methods.go
  internal/pkg/node/methods_test.go
  internal/pkg/node/modifiers.go
  internal/pkg/node/node_test.go
  internal/pkg/node/transformer_test.go
  internal/pkg/node/transformers.go
  internal/pkg/overlay/datastructure.go
  internal/pkg/overlay/funcmap.go
  internal/pkg/overlay/funcmap_test.go
  internal/pkg/overlay/overlay.go
  overlays/wwinit/etc/fstab.ww
  overlays/wwinit/etc/systemd/system/ignition-ww4-disks.service
  overlays/wwinit/etc/systemd/system/local-fs.target.wants/ignition-ww4-disks.service
  overlays/wwinit/etc/systemd/system/local-fs.target.wants/ww4-disks.target
  overlays/wwinit/etc/systemd/system/ww4-disks.target.ww 
  overlays/wwinit/etc/systemd/system/ww4-mounts.ww
  overlays/wwinit/warewulf/ignition.json.ww
  userdocs/contents/disks.rst
  userdocs/index.rst
Labels: stake:suse, stake:openhpc

#808 fix warewulf.conf location for wwclient
  CHANGELOG.md
  internal/app/wwclient/root.go
Labels: bug
