Repository warewulf/warewulf, pull requests merged in 2023-11, with the labels that each got.

#978 Update documentation workflow
  .github/workflows/documentation.yml
Labels: documentation, build

#982 Typo correction SuSE -> SUSE
  userdocs/contents/introduction.rst
Labels: documentation

#985 Quickstart doc updates
  userdocs/quickstart/el7.rst
  userdocs/quickstart/el8.rst
  userdocs/quickstart/el9.rst
  userdocs/quickstart/suse15.rst
Labels: documentation

#984 Typo in setup.rst (then vs. than)
  CONTRIBUTORS.md
  userdocs/contents/setup.rst
Labels: documentation

#953 Update CONTRIBUTING with TSC and initial policies
  .gitignore
  CONTRIBUTING.md
  LICENSE_DEPENDENCIES.md
  MAINTAINING.md
  scripts/update-license-dependencies.sh
Labels: project

#996 Replace development with main
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/check.yml
  .github/workflows/documentation.yml
  internal/app/wwctl/overlay/edit/main.go
  userdocs/conf.py
Labels: documentation, project, testing

#995 Increase linter timeout to 5 minutes
  Makefile
Labels: testing

#983 removed trailing space ww4-disks.target.ww
  Makefile
  overlays/wwinit/etc/systemd/system/ww4-disks.target.ww
Labels: build, overlay

#971 added test for tag from profile
  CHANGELOG.md
  internal/app/wwctl/overlay/list/main.go
  internal/app/wwctl/overlay/list/main_test.go
  internal/app/wwctl/overlay/show/main.go
  internal/app/wwctl/overlay/show/main_test.go
  internal/pkg/node/transformer_test.go
  internal/pkg/node/transformers.go
  internal/pkg/testenv/testenv.go
Labels: bug
