Repository warewulf/warewulf, pull requests merged in 2024-11, with the labels that each got.

#1474 Fix boolean pointer handling
  internal/app/wwctl/node/list/main_test.go
  internal/pkg/node/list.go
  internal/pkg/node/methods.go
Labels: bug

#1471 Fix warewulf.spec.in to use new overlay path
  warewulf.spec.in
Labels: bug

#1478 Remove deadcode from warewulfd
  internal/pkg/warewulfd/daemon.go
Labels: refactor, simplification

#1515 Add deadcode to the github test suite
  .github/workflows/check.yml
Labels: project, build

#1514 Remove unused IsZero function
  internal/pkg/node/datastructure.go
Labels: refactor, simplification

#1518 Simplify passing of arguments through wwctl container exec
  CHANGELOG.md
  internal/app/wwctl/container/exec/main.go
  internal/app/wwctl/container/exec/main_test.go
Labels: bug

#1516 Remove an unnecessary 3s boot from iPXE
  CHANGELOG.md
  etc/ipxe/default.ipxe
Labels: ipxe

#1470 Fix an href in userdocs
  userdocs/contents/disks.rst
Labels: documentation, typo

#1517 Don't package the API in RPM packages by default
  CHANGELOG.md
  warewulf.spec.in
Labels: build

#1448 Updates from CIQ training prep
  CHANGELOG.md
  docs/man/man5/warewulf.conf.5
  etc/warewulf.conf
  internal/pkg/config/buildconfig.go.in
  internal/pkg/config/root.go
  internal/pkg/config/root_test.go
  overlays/debug/internal/debug_test.go
  userdocs/contents/configuration.rst
Labels: documentation, refactor, simplification

#1477 Add support for tagged VLAN interfaces and static routes to network overlays
  CHANGELOG.md
  overlays/NetworkManager/internal/networkmanager_test.go
  overlays/NetworkManager/internal/nodes.conf-vlan
  overlays/NetworkManager/rootfs/etc/NetworkManager/conf.d/ww4-unmanaged.ww
  overlays/NetworkManager/rootfs/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/debian.interfaces/internal/debian_interfaces_test.go
  overlays/debian.interfaces/internal/nodes.conf
  overlays/debian.interfaces/rootfs/etc/network/interfaces.d/default.ww
  overlays/ifcfg/internal/ifcfg_test.go
  overlays/ifcfg/internal/nodes.conf-vlan
  overlays/ifcfg/rootfs/etc/sysconfig/network-scripts/ifcfg.ww
  overlays/ifcfg/rootfs/etc/sysconfig/network-scripts/route.ww
  overlays/wicked/internal/nodes.conf-vlan
  overlays/wicked/internal/wicked_test.go
  overlays/wicked/rootfs/etc/wicked/ifconfig/ifcfg.xml.ww
  userdocs/contents/nodeconfig.rst
Labels: enhancement, overlay

#1533 Use "default" netname during add, set
  internal/app/wwctl/node/add/main.go
  internal/app/wwctl/node/add/root.go
  internal/app/wwctl/profile/add/main.go
  internal/app/wwctl/profile/add/root.go
  internal/pkg/node/flags.go
Labels: bug

#1535 Replace olekukonko/tablewriter with cheynewallace/tabby
  CHANGELOG.md
  go.mod
  go.sum
  internal/app/wwctl/container/list/main.go
  internal/app/wwctl/container/list/main_test.go
  internal/app/wwctl/helper/printhelper.go
  internal/app/wwctl/node/list/main.go
  internal/app/wwctl/node/list/main_test.go
  internal/app/wwctl/profile/list/main.go
  internal/app/wwctl/profile/list/main_test.go
  internal/app/wwctl/table/table.go
  internal/pkg/api/node/list.go
  internal/pkg/api/profile/list.go
Labels: bug

#1532 Resolve redundant file entries in warewulf.spec
  warewulf.spec.in
Labels: bug, build

#1534 replaced errors.Wrap with fmt.Errorf
  CHANGELOG.md
  internal/app/wwctl/container/exec/child/main.go
  internal/app/wwctl/kernel/imprt/main.go
  internal/app/wwctl/node/edit/main.go
  internal/app/wwctl/overlay/delete/main.go
  internal/app/wwctl/overlay/imprt/main.go
  internal/app/wwctl/overlay/list/main.go
  internal/app/wwctl/profile/delete/main.go
  internal/app/wwctl/server/root.go
  internal/pkg/api/container/container.go
  internal/pkg/api/node/add.go
  internal/pkg/api/node/delete.go
  internal/pkg/api/node/edit.go
  internal/pkg/api/profile/add.go
  internal/pkg/api/profile/delete.go
  internal/pkg/api/profile/edit.go
  internal/pkg/api/profile/set.go
  internal/pkg/config/root.go
  internal/pkg/configure/dhcp.go
  internal/pkg/configure/hostfile.go
  internal/pkg/configure/nfs.go
  internal/pkg/configure/ssh.go
  internal/pkg/container/build.go
  internal/pkg/kernel/kernel.go
  internal/pkg/overlay/overlay.go
  internal/pkg/util/util.go
  internal/pkg/warewulfd/daemon.go
  internal/pkg/warewulfd/nodedb.go
  internal/pkg/warewulfd/status.go
  internal/pkg/warewulfd/warewulfd.go
Labels: refactor

#940 don't update ipmi if there is no password
  CHANGELOG.md
  overlays/wwinit/rootfs/warewulf/init.d/50-ipmi
Labels: ipmi

#1540 Remove defaults.conf from userdocs
  userdocs/contents/configuration.rst
Labels: documentation, simplification, unreleased

#1539 Restore skipped tests
  internal/app/wwctl/node/list/main_test.go
  internal/app/wwctl/profile/list/main_test.go
Labels: testing

#1545 Fix `wwctl upgrade config` description
  internal/app/wwctl/upgrade/config/cobra.go
Labels: documentation, typo

#1461 fix issue that initrd fails at downloading runtime overlay with permission denied error, when warewulf secure option in warewulf.conf is enabled
  CHANGELOG.md
  etc/ipxe/default.ipxe
Labels: bug

#1547 Fix panic when adding tag with existing netdev
  CHANGELOG.md
  internal/app/wwctl/node/set/main_test.go
  internal/pkg/api/node/set.go
Labels: bug

#1548 Add test for sending grub.cfg
  CHANGELOG.md
  internal/pkg/warewulfd/provision.go
  internal/pkg/warewulfd/provision_test.go
Labels: bug

#1554 fix typo
  CONTRIBUTORS.md
  userdocs/contents/containers.rst
Labels: documentation, typo

#1549 Fix CHANGELOG for #1004
  CHANGELOG.md
Labels: documentation, typo

#1561 Fix nightly build
  .github/actions/generate/action.yml
  .github/actions/prepare/action.yml
  .github/actions/rpm/action.yml
  .github/workflows/documentation.yml
  warewulf.spec.in
Labels: build

#1563 Format errors in logs as strings
  CHANGELOG.md
  internal/app/wwctl/container/exec/main.go
  internal/pkg/api/container/container.go
  internal/pkg/upgrade/node.go
Labels: bug

#1565 Remove wwctl overlay build --host
  CHANGELOG.md
  internal/app/wwctl/overlay/build/main.go
  internal/app/wwctl/overlay/build/root.go
Labels: simplification
