Repository warewulf/warewulf, pull requests merged in 2024-05, with the labels that each got.

#1207 Only walk the filesystem during syncuser if writing
  CHANGELOG.md
  internal/pkg/container/syncuids.go
Labels: refactor

#1206 Fix parsing of /etc/group during syncuser
  CHANGELOG.md
  internal/pkg/container/syncuids.go
Labels: bug

#1210 v4.5.1 release
  CHANGELOG.md
Labels: project

#1200 fix the nightly release build failure
  .github/actions/generate/action.yml
  .github/actions/rpm/action.yml
  .github/workflows/nightly-release.yml
  CHANGELOG.md
Labels: build

#1211 Update docs for v4.5.1 release
  userdocs/contents/configuration.rst
  userdocs/contents/installation.rst
  userdocs/contributing/development-environment-vagrant.rst
  userdocs/quickstart/debian12.rst
  userdocs/quickstart/el.rst
Labels: documentation

#1187 allow the user to specify ssh key types
  CHANGELOG.md
  etc/warewulf.conf
  internal/app/wwctl/configure/root.go
  internal/app/wwctl/configure/ssh/main.go
  internal/app/wwctl/configure/ssh/root.go
  internal/pkg/config/root.go
  internal/pkg/config/ssh.go
  internal/pkg/configure/ssh.go
  internal/pkg/overlay/datastructure.go
  overlays/debug/rootfs/warewulf/template-variables.md.ww
  overlays/host/rootfs/etc/profile.d/ssh_setup.csh.ww
  overlays/host/rootfs/etc/profile.d/ssh_setup.sh.ww
  userdocs/contents/configuration.rst
Labels: enhancement

#1214 Document HTTP proxy environment variables
  CHANGELOG.md
  userdocs/contents/containers.rst
Labels: documentation

#1222 Update a dependency to address CVE-2024-3727
  CHANGELOG.md
  go.mod
  go.sum
Labels: bug, security

#1227 Parallel overlay building examples.
  CHANGELOG.md
  userdocs/contents/overlays.rst
Labels: documentation
