Repository warewulf/warewulf, pull requests merged in 2024-10, with the labels that each got.

#1201 Spring cleaning - removing dead code and other source tree care
  LICENSE_DEPENDENCIES.md
  Makefile
  Tools.mk
  internal/app/api/API.md
  internal/pkg/api/apiconfig/container/container.go
  internal/pkg/api/node/edit.go
  internal/pkg/api/node/utils.go
  internal/pkg/api/profile/edit.go
  internal/pkg/container/util.go
  internal/pkg/node/helper.go
  internal/pkg/node/methods.go
  internal/pkg/oci/cache.go
  internal/pkg/oci/puller.go
  internal/pkg/util/copyfile.go
  internal/pkg/util/util.go
  internal/pkg/warewulfd/daemon.go
  internal/pkg/wwlog/wwlog.go
  scripts/update-license-dependencies.sh
  ssh_config
  tools.go
Labels: refactor, simplification

#1465 Update boot-management.rst
  userdocs/contents/boot-management.rst
Labels: documentation, typo

#1462 Removed rest of direct yaml.v2 deps
  CHANGELOG.md
  go.mod
  go.sum
  internal/pkg/api/node/list.go
  internal/pkg/api/profile/list.go
  internal/pkg/api/routes/wwapiv1/routes.pb.go
Labels: refactor

#1467 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: documentation

#1466 Remove an erroneous colon suffix from a log message
  internal/pkg/api/node/add.go
Labels: typo

#1459 Make cache directory configureable and add clean command
  CHANGELOG.md
  Variables.mk
  internal/app/wwctl/clean/main.go
  internal/app/wwctl/clean/main_test.go
  internal/app/wwctl/clean/root.go
  internal/app/wwctl/root.go
  internal/pkg/clean/clean.go
  internal/pkg/config/buildconfig.go.in
  internal/pkg/config/root_test.go
  internal/pkg/container/imprt.go
  internal/pkg/overlay/config.go
  internal/pkg/testenv/testenv.go
  internal/pkg/warewulfd/provision_test.go
  internal/pkg/warewulfd/util_test.go
  warewulf.spec.in
Labels: enhancement

#1456 Apply #1454 to main: Set restrictive permissions on /root/.ssh in generic overlay
  CHANGELOG.md
  warewulf.spec.in
Labels: bug, overlay

#1438 wwctl should return non-zero exit code on wwctl kernel sub-commands
  CHANGELOG.md
  internal/app/wwctl/kernel/delete/main.go
  internal/app/wwctl/kernel/imprt/main.go
  internal/app/wwctl/kernel/list/main.go
Labels: refactor, kernel, simplification

#1381 add platform parameter for container import
  CHANGELOG.md
  internal/app/wwctl/container/imprt/main.go
  internal/app/wwctl/container/imprt/root.go
  internal/pkg/api/container/container.go
  internal/pkg/api/routes/v1/routes.proto
  internal/pkg/api/routes/wwapiv1/routes.pb.go
  userdocs/contents/containers.rst
Labels: enhancement

#1458 Fix issue that NetworkManager marks managed interfaces "unmanaged" if they do not have a device specified
  CHANGELOG.md
  overlays/NetworkManager/internal/networkmanager_test.go
  overlays/NetworkManager/internal/nodes_empty_mac.conf
  overlays/NetworkManager/rootfs/etc/NetworkManager/conf.d/ww4-unmanaged.ww
Labels: bug

#1424 Return non-zero exit code on overlay sub-commands
  CHANGELOG.md
  internal/app/wwctl/overlay/build/main.go
  internal/app/wwctl/overlay/chmod/main.go
  internal/app/wwctl/overlay/chown/main.go
  internal/app/wwctl/overlay/create/main.go
  internal/app/wwctl/overlay/delete/main.go
  internal/app/wwctl/overlay/edit/main.go
  internal/app/wwctl/overlay/imprt/main.go
  internal/app/wwctl/overlay/mkdir/main.go
  internal/app/wwctl/overlay/show/main.go
Labels: refactor, user interface, simplification

#1475 Fixes POSIX syntax for several scripts #1464
  CHANGELOG.md
  CONTRIBUTORS.md
  overlays/wwinit/rootfs/init
  overlays/wwinit/rootfs/warewulf/wwinit
  scripts/build-ipxe.sh
Labels: bug, enhancement

#1229 Simplify `wwctl server` command and logging
  CHANGELOG.md
  docs/man/man5/warewulf.conf.5
  include/systemd/warewulfd.service.in
  internal/app/wwctl/server/reload/main.go
  internal/app/wwctl/server/reload/root.go
  internal/app/wwctl/server/restart/main.go
  internal/app/wwctl/server/restart/root.go
  internal/app/wwctl/server/root.go
  internal/app/wwctl/server/start/main.go
  internal/app/wwctl/server/start/root.go
  internal/app/wwctl/server/status/main.go
  internal/app/wwctl/server/status/root.go
  internal/app/wwctl/server/stop/main.go
  internal/app/wwctl/server/stop/root.go
  internal/pkg/warewulfd/daemon.go
  internal/pkg/warewulfd/provision.go
  internal/pkg/warewulfd/util.go
  internal/pkg/warewulfd/warewulfd.go
  internal/pkg/wwlog/wwlog.go
  internal/pkg/wwlog/wwlog_test.go
  userdocs/contents/configuration.rst
  userdocs/contents/initialization.rst
  userdocs/contributing/development-environment-kvm.rst
  userdocs/contributing/development-environment-vagrant.rst
  userdocs/contributing/development-environment-vbox.rst
Labels: warewulfd
