Repository warewulf/warewulf, pull requests merged in 2024-09, with the labels that each got.

#1374 Fix typo in "profile with name ... already exists" message
  internal/pkg/api/profile/profile.go
Labels: typo

#1372 Add LOGROTATEDIR to Defaults.mk
  CONTRIBUTORS.md
  Variables.mk
Labels: build

#1360 refine `wwctl configure` error handling
  CHANGELOG.md
  internal/pkg/configure/dhcp.go
  internal/pkg/configure/hostfile.go
  internal/pkg/configure/ssh.go
  internal/pkg/configure/tftp.go
Labels: bug

#1369 docs: fix dracut build command in docs
  CHANGELOG.md
  userdocs/contents/boot-management.rst
Labels: documentation

#1350 Refactor url build in wwclient with url.URL
  CHANGELOG.md
  internal/app/wwclient/root.go
Labels: refactor

#1379 Add rules for TSC member and chair selection
  CONTRIBUTING.md
  MAINTAINING.md
Labels: documentation, project, discuss

#1142 adding WAREWULF_OCI vars to wwctl
  CHANGELOG.md
  internal/app/wwctl/container/imprt/main.go
  internal/app/wwctl/container/imprt/root.go
  internal/pkg/api/container/container.go
  internal/pkg/api/routes/v1/routes.proto
  internal/pkg/api/routes/wwapiv1/routes.pb.go
  userdocs/contents/containers.rst
Labels: enhancement

#1380 Fixed node overlays overrides of profile overlays
  CHANGELOG.md
  internal/app/wwctl/node/list/main_test.go
  internal/pkg/node/constuctors_test.go
  internal/pkg/node/methods.go
Labels: bug

#1383 Additional guidance when syncuser conflicts
  CHANGELOG.md
  internal/pkg/container/syncuids.go
Labels: documentation

#1365 add cow option for binds
  CHANGELOG.md
  internal/app/wwctl/container/exec/child/main.go
  internal/app/wwctl/container/exec/main.go
  internal/app/wwctl/container/exec/root.go
  internal/app/wwctl/container/shell/root.go
  internal/pkg/config/mounts.go
  internal/pkg/container/mountpoints.go
  userdocs/contents/containers.rst
Labels: enhancement

#1351 Dracut boot refinement
  CHANGELOG.md
  CONTRIBUTORS.md
  dracut/modules.d/90wwinit/load-wwinit.sh
  dracut/modules.d/90wwinit/module-setup.sh
  dracut/modules.d/90wwinit/parse-wwinit.sh
  etc/grub/grub.cfg.ww
  etc/ipxe/dracut.ipxe
  warewulf.spec.in
Labels: bug

#1387 Return an error indicating that name should not contain colon when importing containers
  CHANGELOG.md
  internal/pkg/oci/puller.go
  internal/pkg/oci/puller_test.go
Labels: bug

#1392 Improve network interface documentation
  userdocs/contents/nodeconfig.rst
  userdocs/contents/overlays.rst
Labels: documentation

#1396 Set mpol=interleave on dracut tmpfs
  CHANGELOG.md
  dracut/modules.d/90wwinit/load-wwinit.sh
  overlays/wwinit/rootfs/init
Labels: enhancement

#822 Init rootfs fixes
  CHANGELOG.md
  CONTRIBUTORS.md
  overlays/wwinit/rootfs/init
Labels: wwinit

#1401 Init rootfs fixes
  CHANGELOG.md
  CONTRIBUTORS.md
  overlays/wwinit/rootfs/init
Labels: bug

#1407 Return non-zero exit code on container copy failure
  CHANGELOG.md
  internal/app/wwctl/container/copy/main.go
Labels: bug

#1404 Add flag --build to wwctl container copy, default false
  CHANGELOG.md
  internal/app/wwctl/container/copy/main.go
  internal/app/wwctl/container/copy/main_test.go
  internal/app/wwctl/container/copy/root.go
  internal/pkg/api/container/container.go
  internal/pkg/api/routes/v1/routes.proto
  internal/pkg/api/routes/wwapiv1/routes.pb.go
  internal/pkg/container/build.go
  internal/pkg/container/util.go
Labels: enhancement

#1400 fix autodetected kernel sorting
  CHANGELOG.md
  go.mod
  go.sum
  internal/pkg/kernel/kernel.go
  internal/pkg/kernel/kernel_test.go
Labels: bug

#1412 Fix panic on container import
  CHANGELOG.md
  internal/pkg/container/imprt.go
Labels: bug

#1358 Add --syncuser flag to wwctl shell
  CHANGELOG.md
  internal/app/wwctl/container/exec/main.go
  internal/app/wwctl/container/shell/main.go
  internal/app/wwctl/container/shell/root.go
Labels: bug

#1410 Configure onboot for NetworkManager, debian networking, and wicked
  CHANGELOG.md
  overlays/wwinit/rootfs/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/wwinit/rootfs/etc/network/interfaces.d/default.ww
  overlays/wwinit/rootfs/etc/wicked/ifconfig/ifcfg.xml.ww
Labels: bug

#1408 Fix excessive line spacing issue when listing nodes
  CHANGELOG.md
  internal/app/wwctl/container/list/main.go
  internal/app/wwctl/container/list/main_test.go
  internal/app/wwctl/container/rename/main_test.go
  internal/app/wwctl/helper/printhelper.go
  internal/app/wwctl/node/list/main.go
  internal/app/wwctl/node/list/main_test.go
  internal/app/wwctl/profile/list/main.go
  internal/app/wwctl/profile/list/main_test.go
Labels: bug

#1418 Fix a "wicked" ifcfg overlay regression
  overlays/wwinit/rootfs/etc/wicked/ifconfig/ifcfg.xml.ww
Labels: bug

#1234 New troubleshooting guide
  CHANGELOG.md
  userdocs/contents/troubleshooting.rst
  userdocs/index.rst
Labels: documentation, stake:ciq

#1395 Fix panic when getting a long container list before building the container
  CHANGELOG.md
  Makefile
  internal/app/wwctl/container/list/main_test.go
  internal/app/wwctl/container/list/root.go
  internal/pkg/api/container/container.go
  internal/pkg/testenv/testenv.go
Labels: bug

#1426 Fixes for EL quickstart
  CHANGELOG.md
  internal/app/wwctl/container/imprt/root.go
  userdocs/quickstart/el.rst
Labels: documentation

#1428 Update SELinux documentation to address rootfstype=ramfs
  CHANGELOG.md
  userdocs/contents/security.rst
Labels: documentation

#1430 Add workaround documentation for importing containers with sockets
  CHANGELOG.md
  userdocs/contents/containers.rst
Labels: documentation

#1429 Building ipxe locally
  CHANGELOG.md
  userdocs/contents/boot-management.rst
  userdocs/contents/containers.rst
  userdocs/contents/disks.rst
Labels: documentation

#1427 Document that ignition is not available for Rocky Linux 8
  CHANGELOG.md
  userdocs/contents/disks.rst
Labels: documentation

#1432 Change the permission of overlay dir to `0750` and generated overlays to `0660`
  CHANGELOG.md
  internal/app/wwctl/overlay/build/main.go
  internal/pkg/overlay/overlay.go
Labels: bug

#1431 `wwctl node set` requires mandatory pattern input
  CHANGELOG.md
  internal/app/wwctl/node/set/root.go
Labels: bug

#1425 Fix a missing string quote
  overlays/wwinit/rootfs/init
Labels: bug
