Repository warewulf/warewulf, pull requests merged in 2024-02, with the labels that each got.

#1034 move dnsmasq template into etc
  overlays/host/etc/dnsmasq.d/ww4-hosts.conf.ww
Labels: bug

#1072 add DNS fields to multiple managed templates
  CHANGELOG.md
  overlays/wwinit/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/wwinit/etc/resolv.conf.ww
  overlays/wwinit/etc/sysconfig/network-scripts/ifcfg.ww
Labels: enhancement

#1037 removed double entries from paths
  CHANGELOG.md
  Makefile
  internal/pkg/config/buildconfig.go.in
  internal/pkg/config/mounts.go
  internal/pkg/config/root_test.go
  internal/pkg/config/tftp.go
  internal/pkg/config/warewulf.go
  internal/pkg/configure/tftp.go
  internal/pkg/node/constructors.go
  internal/pkg/testenv/testenv.go
  internal/pkg/version/version.go
  internal/pkg/warewulfd/copyshim.go
Labels: bug, confirmed

#1089 Fix sphinx warnings
  userdocs/conf.py
  userdocs/contents/disks.rst
  userdocs/contents/example-templates.rst
  userdocs/contents/ipmi.rst
  userdocs/contents/provisioning.rst
  userdocs/contents/stateless.rst
  userdocs/contents/templating.rst
  userdocs/contributing/debugging.rst
  userdocs/contributing/development-environment-kvm.rst
  userdocs/contributing/development-environment-vagrant.rst
  userdocs/contributing/development-environment-vbox.rst
  userdocs/index.rst
  userdocs/quickstart/el7.rst
Labels: documentation

#1090 Henkela disks docs
  CONTRIBUTORS.md
  userdocs/contents/disks.rst
Labels: documentation

#1043 Documentation for mulitple networks
  CHANGELOG.md
  userdocs/contents/nodeconfig.rst
  userdocs/contents/setup.rst
Labels: documentation

#1041 Document installation instructions for dnsmasq
  CHANGELOG.md
  userdocs/contents/dnsmasq.rst
Labels: documentation

#862 Userdocs fact check and audit
  etc/warewulf.conf
  go.mod
  userdocs/contents/configuration.rst
  userdocs/contents/containers.rst
  userdocs/contents/initialization.rst
  userdocs/contents/installation.rst
  userdocs/contents/kernel.rst
  userdocs/contents/nodeconfig.rst
  userdocs/contents/profiles.rst
  userdocs/contents/setup.rst
  userdocs/contents/stateless.rst
  userdocs/contents/wwctl.rst
  userdocs/index.rst
Labels: documentation

#1086 Move overlays to rootfs and and set ownership
  CHANGELOG.md
  Makefile
  overlays/debug/rootfs/warewulf/template-variables.md.ww
  overlays/generic/rootfs/etc/group.ww
  overlays/generic/rootfs/etc/hosts.ww
  overlays/generic/rootfs/etc/passwd.ww
  overlays/generic/rootfs/root/.ssh/authorized_keys.ww
  overlays/host/rootfs/etc/dhcp/dhcpd.conf.ww
  overlays/host/rootfs/etc/dhcpd.conf
  overlays/host/rootfs/etc/dhcpd.conf.ww
  overlays/host/rootfs/etc/dnsmasq.d/ww4-hosts.conf.ww
  overlays/host/rootfs/etc/exports.ww
  overlays/host/rootfs/etc/hosts.ww
  overlays/host/rootfs/etc/profile.d/ssh_setup.csh
  overlays/host/rootfs/etc/profile.d/ssh_setup.sh
  overlays/wwinit/rootfs/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/wwinit/rootfs/etc/fstab.ww
  overlays/wwinit/rootfs/etc/hostname.ww
  overlays/wwinit/rootfs/etc/issue.ww
  overlays/wwinit/rootfs/etc/network/interfaces
  overlays/wwinit/rootfs/etc/network/interfaces.d/default.ww
  overlays/wwinit/rootfs/etc/resolv.conf.ww
  overlays/wwinit/rootfs/etc/ssh/ssh_host_dsa_key.pub.ww
  overlays/wwinit/rootfs/etc/ssh/ssh_host_dsa_key.ww
  overlays/wwinit/rootfs/etc/ssh/ssh_host_ecdsa_key.pub.ww
  overlays/wwinit/rootfs/etc/ssh/ssh_host_ecdsa_key.ww
  overlays/wwinit/rootfs/etc/ssh/ssh_host_ed25519_key.pub.ww
  overlays/wwinit/rootfs/etc/ssh/ssh_host_ed25519_key.ww
  overlays/wwinit/rootfs/etc/ssh/ssh_host_rsa_key.pub.ww
  overlays/wwinit/rootfs/etc/ssh/ssh_host_rsa_key.ww
  overlays/wwinit/rootfs/etc/sysconfig/network-scripts/ifcfg.ww
  overlays/wwinit/rootfs/etc/sysconfig/network.ww
  overlays/wwinit/rootfs/etc/systemd/network/10-persistent-net.link.ww
  overlays/wwinit/rootfs/etc/systemd/system/ignition-ww4-disks.service
  overlays/wwinit/rootfs/etc/systemd/system/local-fs.target.wants/ignition-ww4-disks.service
  overlays/wwinit/rootfs/etc/systemd/system/local-fs.target.wants/ww4-disks.target
  overlays/wwinit/rootfs/etc/systemd/system/multi-user.target.wants/wwclient.service
  overlays/wwinit/rootfs/etc/systemd/system/ww4-disks.target.ww
  overlays/wwinit/rootfs/etc/systemd/system/ww4-mounts.ww
  overlays/wwinit/rootfs/etc/systemd/system/wwclient.service
  overlays/wwinit/rootfs/etc/udev/rules.d/70-ww4-netname.rules.ww
  overlays/wwinit/rootfs/etc/warewulf/warewulf.conf.ww
  overlays/wwinit/rootfs/etc/wicked/ifconfig/ifcfg.xml.ww
  overlays/wwinit/rootfs/init
  overlays/wwinit/rootfs/warewulf/config.ww
  overlays/wwinit/rootfs/warewulf/ignition.json.ww
  overlays/wwinit/rootfs/warewulf/init.d/20-loopback
  overlays/wwinit/rootfs/warewulf/init.d/50-ipmi
  overlays/wwinit/rootfs/warewulf/init.d/75-vnfs_fixes
  overlays/wwinit/rootfs/warewulf/init.d/80-wwclient.ww
  overlays/wwinit/rootfs/warewulf/init.d/90-selinux
  overlays/wwinit/rootfs/warewulf/wwinit
  warewulf.spec.in
Labels: bug

#1106 Install Graphviz in userdocs CI workflow
  .github/workflows/documentation.yml
Labels: documentation, project
