Repository warewulf/warewulf, pull requests merged in 2024-12, with the labels that each got.

#1564 Use a sentinel file to determine container readonly state
  CHANGELOG.md
  internal/app/wwctl/container/exec/child/main.go
  internal/pkg/container/util.go
  internal/pkg/util/util.go
  userdocs/contents/containers.rst
Labels: bug, enhancement

#1575 Disable deadcode check for previous golang versions
  .github/workflows/check.yml
Labels: bug, build

#1577 Remove toolchain directive from go.mod
  .github/workflows/check.yml
  go.mod
Labels: bug, testing

#1580 Update github.com/opencontainers/runc to 1.1.14
  CHANGELOG.md
  go.mod
  go.sum
Labels: security

#1587 Support importing containers from directories containing a socket
  CHANGELOG.md
  go.mod
  go.sum
  internal/pkg/container/imprt_test.go
Labels: bug

#1590 Package the netplan overlay
  warewulf.spec.in
Labels: bug, nochangelog

#1592 Added firewalld and nftables setup to configuration.rst
  userdocs/contents/configuration.rst
Labels: documentation

#1303 create soft links from overlays
  CHANGELOG.md
  internal/pkg/overlay/funcmap.go
  internal/pkg/overlay/overlay.go
  overlays/localtime/internal/localtime_test.go
  overlays/localtime/internal/nodes.conf
  overlays/localtime/rootfs/etc/localtime.ww
  userdocs/contents/templating.rst
  warewulf.spec.in
Labels: enhancement

#1595 Configure nodes.conf dynamically from config
  CHANGELOG.md
  Makefile
  internal/app/wwctl/configure/dhcp/root.go
  internal/app/wwctl/configure/hostfile/root.go
  internal/app/wwctl/configure/nfs/root.go
  internal/app/wwctl/configure/ssh/root.go
  internal/app/wwctl/container/copy/root.go
  internal/app/wwctl/container/rename/root.go
  internal/app/wwctl/genconf/completions/root.go
  internal/app/wwctl/genconf/man/root.go
  internal/app/wwctl/genconf/reference/root.go
  internal/app/wwctl/genconf/warewulfconf/print/root.go
  internal/app/wwctl/node/export/root.go
  internal/app/wwctl/node/list/main_test.go
  internal/app/wwctl/node/set/main_test.go
  internal/app/wwctl/overlay/chmod/root.go
  internal/app/wwctl/overlay/chown/root.go
  internal/app/wwctl/overlay/create/root.go
  internal/app/wwctl/power/root.go
  internal/app/wwctl/profile/list/main_test.go
  internal/app/wwctl/root.go
  internal/app/wwctl/upgrade/cobra.go
  internal/app/wwctl/upgrade/config/cobra.go
  internal/app/wwctl/upgrade/nodes/cobra.go
  internal/pkg/api/util/util.go
  internal/pkg/config/buildconfig.go.in
  internal/pkg/node/constructors.go
  internal/pkg/node/modifiers.go
  internal/pkg/testenv/testenv.go
  internal/pkg/warewulfd/util.go
Labels: bug

#1558 Introduce site overlays
  CHANGELOG.md
  Makefile
  Variables.mk
  internal/app/wwctl/node/sensors/root_test.go
  internal/app/wwctl/overlay/chmod/main.go
  internal/app/wwctl/overlay/chown/main.go
  internal/app/wwctl/overlay/create/main.go
  internal/app/wwctl/overlay/delete/main.go
  internal/app/wwctl/overlay/edit/main.go
  internal/app/wwctl/overlay/imprt/main.go
  internal/app/wwctl/overlay/list/main.go
  internal/app/wwctl/overlay/list/main_test.go
  internal/app/wwctl/overlay/mkdir/main.go
  internal/app/wwctl/overlay/show/main.go
  internal/app/wwctl/overlay/show/main_test.go
  internal/app/wwctl/power/cycle/root_test.go
  internal/app/wwctl/power/off/root_test.go
  internal/app/wwctl/power/on/root_test.go
  internal/app/wwctl/power/reset/root_test.go
  internal/app/wwctl/power/soft/root_test.go
  internal/app/wwctl/power/status/root_test.go
  internal/pkg/config/buildconfig.go.in
  internal/pkg/configure/hostfile.go
  internal/pkg/oci/defaults.go
  internal/pkg/overlay/config.go
  internal/pkg/overlay/datastructure.go
  internal/pkg/overlay/overlay.go
  internal/pkg/overlay/overlay_test.go
  internal/pkg/power/ipmitool.go
  internal/pkg/testenv/testenv.go
  internal/pkg/upgrade/config.go
  internal/pkg/upgrade/config_test.go
  internal/pkg/warewulfd/util.go
  overlays/debug/internal/debug_test.go
  overlays/debug/rootfs/warewulf/template-variables.md.ww
  userdocs/contents/overlays.rst
  warewulf.spec.in
Labels: enhancement, overlay
