Repository warewulf/warewulf, pull requests merged in 2024-04, with the labels that each got.

#1161 Never attempt to build protocol buffers offline
  CHANGELOG.md
  Makefile
Labels: bug, build

#1170 change ipxe location for SUSE based distros at build time
  CHANGELOG.md
  warewulf.spec.in
Labels: bug, backport:4.5.x

#1173 Run tests against PRs to v4.*.x branches
  .github/workflows/check.yml
Labels: project, build

#1162 Calculate VERSION and RELEASE dynamically from git
  CHANGELOG.md
  Makefile
  Variables.mk
  scripts/get-version.sh
  scripts/rpm-release.sh
  scripts/rpm-version.sh
Labels: enhancement, build, backport:4.5.x

#1181 Update overlays.rst
  userdocs/contents/overlays.rst
Labels: documentation

#1184 changed typo in the word belonging
  userdocs/contents/containers.rst
Labels: documentation, backport:4.5.x, typo

#1178 Update CHANGELOG to anticipate v4.5.1
  CHANGELOG.md
Labels: documentation, project

#1193 Don't build the API for CentOS 7
  CHANGELOG.md
  Makefile
  warewulf.spec.in
Labels: build

#1194 Update tagged-release to accommodate new artifact names
  .github/workflows/tagged-release.yml
Labels: build

#1196 Fetch tags during tagged-release
  .github/workflows/tagged-release.yml
Labels: build

#1197 Fetch all history during tagged-release
  .github/workflows/tagged-release.yml
Labels: build

#1198 Use lightweight tags when generating version
  scripts/get-version.sh
Labels: build

#1145 Tests and fix for shim and grub detection on aarch64
  CHANGELOG.md
  internal/app/wwctl/kernel/imprt/main.go
  internal/pkg/api/apiconfig/container/container.go
  internal/pkg/api/container/container.go
  internal/pkg/container/kernel.go
  internal/pkg/container/shimgrub.go
  internal/pkg/container/shimgrub_test.go
  internal/pkg/kernel/kernel.go
  internal/pkg/warewulfd/provision.go
Labels: bug
