Repository warewulf/warewulf, pull requests merged in 2024-08, with the labels that each got.

#1309 sanitize wwclient url data
  CHANGELOG.md
  internal/app/wwclient/root.go
Labels: bug

#1297 removed dead `boot method` from defaults.conf
  internal/pkg/node/constructors.go
Labels: refactor

#1295 Check for empty container var
  CHANGELOG.md
  etc/grub/grub.cfg.ww
  etc/ipxe/default.ipxe
  etc/ipxe/dracut.ipxe
Labels: enhancement

#1284 updated documenation regarding fswipe
  userdocs/contents/disks.rst
Labels: documentation, build

#1276 logrotate support
  CHANGELOG.md
  Makefile
  Variables.mk
  etc/logrotate.d/warewulfd.conf
  warewulf.spec.in
Labels: enhancement

#1305 Update selinux documentation to reference an example
  CHANGELOG.md
  userdocs/contents/security.rst
Labels: documentation

#1367 Fix old links that pointed to warewulf-web
  CHANGELOG.md
  userdocs/contributing/documentation.rst
Labels: documentation
