Repository warewulf/warewulf, pull requests merged in 2024-03, with the labels that each got.

#1124 Update CHANGELOG for v4.5.0
  .github/actions/prepare/action.yml
  CHANGELOG.md
  userdocs/contents/setup.rst
  warewulf.spec.in
Labels: documentation

#1125 Restore el7 quickstart
  userdocs/index.rst
  userdocs/quickstart/el7.rst
Labels: documentation

#1126 Fix ipxe-bootimgs in warewulf.spec.in for el7
  warewulf.spec.in
Labels: build

#1127 Merge Enterprise Linux quickstarts
  userdocs/index.rst
  userdocs/quickstart/el.rst
  userdocs/quickstart/el7.rst
  userdocs/quickstart/el8.rst
  userdocs/quickstart/el9.rst
Labels: documentation

#1030 Add string functions from sprig for use in templates
  CHANGELOG.md
  go.mod
  go.sum
  internal/pkg/overlay/overlay.go
  internal/pkg/warewulfd/provision.go
  overlays/wwinit/rootfs/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/wwinit/rootfs/etc/systemd/system/ww4-disks.target.ww
  overlays/wwinit/rootfs/etc/systemd/system/ww4-mounts.ww
Labels: enhancement

#1119 Fixed profile list bug
  CHANGELOG.md
  internal/app/wwctl/profile/list/main.go
  internal/pkg/api/profile/list.go
Labels: discuss, needs confirmation

#1132 Fix a formatting error hiding GRUB configuration
  CHANGELOG.md
  userdocs/contents/boot-management.rst
Labels: documentation

#1140 Replace slice in templates with sprig substr
  CHANGELOG.md
  overlays/wwinit/rootfs/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/wwinit/rootfs/etc/resolv.conf.ww
  overlays/wwinit/rootfs/etc/sysconfig/network-scripts/ifcfg.ww
  overlays/wwinit/rootfs/etc/systemd/system/ww4-disks.target.ww
  overlays/wwinit/rootfs/etc/systemd/system/ww4-mounts.ww
Labels: bug

#1144 added more aliases for wwctl commands
  CHANGELOG.md
  internal/app/wwctl/container/delete/root.go
  internal/app/wwctl/container/imprt/root.go
  internal/app/wwctl/container/shell/root.go
  internal/app/wwctl/container/show/root.go
  internal/app/wwctl/kernel/delete/root.go
  internal/app/wwctl/kernel/imprt/root.go
  internal/app/wwctl/node/add/root.go
  internal/app/wwctl/node/delete/root.go
  internal/app/wwctl/node/set/root.go
  internal/app/wwctl/overlay/create/root.go
  internal/app/wwctl/overlay/delete/root.go
  internal/app/wwctl/profile/add/root.go
  internal/app/wwctl/profile/delete/root.go
  internal/app/wwctl/profile/set/root.go
Labels: enhancement

#1149 upgrade golang version to 1.20
  .github/workflows/check.yml
  CHANGELOG.md
  go.mod
Labels: discuss, needs confirmation

#1141 Document overriding paths in warewulf.conf
  CHANGELOG.md
  userdocs/contents/configuration.rst
Labels: documentation
