Repository warewulf/warewulf, pull requests merged in 2024-01, with the labels that each got.

#1028 Update Slack invite for Warewulf Slack
  userdocs/contributing/contributing.rst
Labels: documentation

#1003 separate writer for wwlog.Info
  CHANGELOG.md
  internal/pkg/wwlog/wwlog.go
Labels: bug

#1040 Update path to warewulf-node-images
  containers/README.md
Labels: documentation

#859 grub netboot implementation
  CHANGELOG.md
  Makefile
  etc/grub/chainload.ww
  etc/grub/grub.cfg.ww
  go.mod
  internal/app/wwctl/container/delete/main.go
  internal/app/wwctl/container/exec/main.go
  internal/app/wwctl/container/imprt/main.go
  internal/app/wwctl/profile/delete/main.go
  internal/pkg/api/profile/profile.go
  internal/pkg/config/warewulf.go
  internal/pkg/configure/tftp.go
  internal/pkg/container/shimgrub.go
  internal/pkg/node/constructors.go
  internal/pkg/node/datastructure.go
  internal/pkg/node/util.go
  internal/pkg/overlay/datastructure.go
  internal/pkg/warewulfd/copyshim.go
  internal/pkg/warewulfd/parser.go
  internal/pkg/warewulfd/provision.go
  internal/pkg/warewulfd/provision_test.go
  internal/pkg/warewulfd/util.go
  internal/pkg/warewulfd/warewulfd.go
  overlays/host/etc/dhcp/dhcpd.conf.ww
  overlays/host/etc/dhcpd.conf.ww
  overlays/wwinit/warewulf/init.d/80-wwclient
  userdocs/conf.py
  userdocs/contents/boot-management.rst
  userdocs/contents/security.rst
  userdocs/index.rst
  warewulf.spec.in
Labels: enhancement, stake:suse

#952 overlays from different profiles are merged
  CHANGELOG.md
  internal/pkg/node/constuctors_test.go
  internal/pkg/node/methods.go
  tools.go
Labels: enhancement

#934 Fix empty kernel modules and drivers
  CHANGELOG.md
  internal/app/wwctl/kernel/imprt/main.go
  internal/pkg/kernel/kernel.go
  internal/pkg/kernel/kernel_test.go
  internal/pkg/overlay/overlay_test.go
  internal/pkg/util/cpio.go
  internal/pkg/util/util.go
Labels: bug

#1048 Remove whitespace damage
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/actions/generate/action.yml
  .github/workflows/changelog-enforcer.yml
  .github/workflows/nightly.yml
  CHANGELOG.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  Dockerfile
  container-scripts/README.md
  container-scripts/config-warewulf
  container-scripts/label-install
  container-scripts/warewulf-container-manage.sh
  container-scripts/warewulf.service
  etc/grub/grub.cfg.ww
  internal/app/wwctl/node/list/main_test.go
  internal/pkg/api/routes/v1/routes.proto
  overlays/host/etc/dhcp/dhcpd.conf.ww
  userdocs/contents/boot-management.rst
  userdocs/contents/dnsmasq.rst
  userdocs/contents/example-templates.rst
  userdocs/contents/provisioning.rst
  userdocs/contents/security.rst
  userdocs/contents/templating.rst
  userdocs/contributing/debugging.rst
  userdocs/contributing/development-environment-vagrant.rst
  userdocs/index.rst
  userdocs/quickstart/debian12.rst
Labels: refactor
