Repository warewulf/warewulf, pull requests merged in 2024-06, with the labels that each got.

#1228 Replace ref to docusaurus with Sphinx
  CHANGELOG.md
  userdocs/contributing/documentation.rst
Labels: documentation

#1219 Point to warewulf github in installation docs
  CHANGELOG.md
  userdocs/contents/installation.rst
Labels: documentation

#1150 add CIDR format to warewulf.conf parse
  CHANGELOG.md
  internal/pkg/config/root.go
Labels: bug

#1212 Refactor syncuser to reduce walks of the container fs
  CHANGELOG.md
  internal/app/wwctl/container/exec/main.go
  internal/app/wwctl/container/syncuser/main.go
  internal/pkg/api/container/container.go
  internal/pkg/container/syncuids.go
Labels: bug

#1231 Call SSH(keys) on configure --all
  CHANGELOG.md
  internal/app/wwctl/configure/main.go
Labels: bug

#1191 Dracut initramfs boot
  CHANGELOG.md
  Makefile
  Variables.mk
  dracut/modules.d/90wwinit/load-wwinit.sh
  dracut/modules.d/90wwinit/module-setup.sh
  dracut/modules.d/90wwinit/parse-wwinit.sh
  etc/grub/grub.cfg.ww
  etc/ipxe/dracut.ipxe
  internal/pkg/container/config.go
  internal/pkg/container/config_test.go
  internal/pkg/warewulfd/parser.go
  internal/pkg/warewulfd/provision.go
  internal/pkg/warewulfd/provision_test.go
  overlays/wwinit/rootfs/etc/NetworkManager/conf.d/ww4-discard-configuration.conf
  overlays/wwinit/rootfs/warewulf/init.d/90-selinux
  userdocs/contents/boot-management.rst
  warewulf.spec.in
Labels: enhancement

#1182 Fix overlay directory location/creation
  CHANGELOG.md
  internal/app/wwctl/container/exec/child/main.go
  internal/app/wwctl/container/exec/main.go
  internal/app/wwctl/container/exec/root.go
  internal/pkg/config/root.go
  internal/pkg/config/root_test.go
  internal/pkg/container/config.go
Labels: bug

#1251 Fix regression in container exec argument parsing
  CHANGELOG.md
  internal/app/wwctl/container/exec/main.go
  internal/app/wwctl/container/exec/main_test.go
  internal/pkg/testenv/testenv.go
Labels: bug
