Repository warewulf/warewulf, pull requests merged in 2024-07, with the labels that each got.

#1285 Capture "broken" symlinks during container build
  CHANGELOG.md
  internal/pkg/util/util.go
  internal/pkg/util/util_test.go
Labels: bug

#1263 Restore previous behavior of static dhcp
  CHANGELOG.md
  overlays/host/rootfs/etc/dhcp/dhcpd.conf.ww
Labels: bug

#1238 fix the issue that new files created via wwctl overlay edit have permission 755 && removing lines during wwctl overlay edit didn't work
  CHANGELOG.md
  internal/app/wwctl/overlay/edit/main.go
Labels: bug, overlay

#1292 mount /sys and /run during container exec
  CHANGELOG.md
  internal/app/wwctl/container/exec/child/main.go
Labels: enhancement

#1286 ignore +:: style lines in passwd/group
  CHANGELOG.md
  internal/pkg/container/syncuids.go
  internal/pkg/container/syncuids_test.go
Labels: enhancement

#1260 Fix wwctl overlay list completion
  CHANGELOG.md
  internal/app/wwctl/overlay/list/root.go
Labels: bug, overlay

#1268 Accept + within kernel versions
  CHANGELOG.md
  internal/pkg/kernel/kernel.go
  internal/pkg/kernel/kernel_test.go
Labels: bug

#1294 Prevent make dist from including previous dists
  Makefile
Labels: build

#1304 Move dracut docs to their own heading
  userdocs/contents/boot-management.rst
Labels: documentation, refactor

#1313 fix the failure when updating overlay files existing on different par…
  CHANGELOG.md
  internal/app/wwctl/overlay/edit/main.go
Labels: bug
