Repository warewulf/warewulf, pull requests merged in 2025-01, with the labels that each got.

#1609 Add note in userdoc regarding dracut and machine-id
  CHANGELOG.md
  CONTRIBUTORS.md
  userdocs/contents/boot-management.rst
Labels: documentation

#1604 Parallel and optimized overlay builds
  CHANGELOG.md
  go.mod
  go.sum
  internal/app/wwctl/container/exec/child/main.go
  internal/app/wwctl/overlay/build/main.go
  internal/app/wwctl/overlay/build/root.go
  internal/app/wwctl/overlay/imprt/main.go
  internal/app/wwctl/overlay/imprt/root.go
  internal/app/wwctl/overlay/show/main.go
  internal/pkg/config/buildconfig.go.in
  internal/pkg/config/dhcp.go
  internal/pkg/config/mounts.go
  internal/pkg/config/nfs.go
  internal/pkg/config/util.go
  internal/pkg/configure/hostfile.go
  internal/pkg/overlay/datastructure.go
  internal/pkg/overlay/overlay.go
  internal/pkg/overlay/overlay_test.go
  internal/pkg/testenv/testenv.go
  internal/pkg/util/cpio.go
  internal/pkg/util/util.go
  internal/pkg/util/util_test.go
  internal/pkg/warewulfd/util.go
  userdocs/contents/overlays.rst
Labels: enhancement

#1598 Support nested profiles
  CHANGELOG.md
  internal/app/wwctl/clean/main_test.go
  internal/app/wwctl/node/list/main_test.go
  internal/app/wwctl/node/set/main_test.go
  internal/app/wwctl/profile/list/main_test.go
  internal/app/wwctl/profile/set/main_test.go
  internal/pkg/api/node/list.go
  internal/pkg/api/profile/list.go
  internal/pkg/container/shimgrub_test.go
  internal/pkg/container/syncuids_test.go
  internal/pkg/node/constructors.go
  internal/pkg/node/constructors_test.go
  internal/pkg/node/datastructure.go
  internal/pkg/node/fields.go
  internal/pkg/node/fields_test.go
  internal/pkg/node/list.go
  internal/pkg/node/mergo.go
  internal/pkg/node/mergo_test.go
  internal/pkg/node/methods.go
  internal/pkg/node/util_test.go
  internal/pkg/overlay/funcmap_test.go
  internal/pkg/upgrade/node.go
  internal/pkg/upgrade/node_test.go
  internal/pkg/warewulfd/provision_test.go
  userdocs/contents/profiles.rst
Labels: enhancement

#1603 Add wwctl container <exec|shell> --build=false
  CHANGELOG.md
  internal/app/wwctl/container/exec/child/main.go
  internal/app/wwctl/container/exec/main.go
  internal/app/wwctl/container/exec/main_test.go
  internal/app/wwctl/container/exec/root.go
  internal/app/wwctl/container/shell/main.go
  internal/app/wwctl/container/shell/root.go
  userdocs/contents/containers.rst
Labels: enhancement

#1612 Benchmark test for overlay build
  internal/app/wwctl/clean/main_test.go
  internal/app/wwctl/container/copy/main_test.go
  internal/app/wwctl/container/exec/main_test.go
  internal/app/wwctl/container/kernels/main_test.go
  internal/app/wwctl/container/list/main_test.go
  internal/app/wwctl/container/rename/main_test.go
  internal/app/wwctl/node/add/main_test.go
  internal/app/wwctl/node/list/main_test.go
  internal/app/wwctl/node/sensors/root_test.go
  internal/app/wwctl/node/set/main_test.go
  internal/app/wwctl/overlay/build/main_test.go
  internal/app/wwctl/overlay/list/main_test.go
  internal/app/wwctl/overlay/show/main_test.go
  internal/app/wwctl/power/cycle/root_test.go
  internal/app/wwctl/power/off/root_test.go
  internal/app/wwctl/power/on/root_test.go
  internal/app/wwctl/power/reset/root_test.go
  internal/app/wwctl/power/soft/root_test.go
  internal/app/wwctl/power/status/root_test.go
  internal/app/wwctl/profile/add/main_test.go
  internal/app/wwctl/profile/list/main_test.go
  internal/app/wwctl/profile/set/main_test.go
  internal/pkg/container/imprt_test.go
  internal/pkg/container/initramfs_test.go
  internal/pkg/kernel/kernel_test.go
  internal/pkg/node/fields_test.go
  internal/pkg/node/mergo_test.go
  internal/pkg/overlay/overlay_test.go
  internal/pkg/testenv/testenv.go
  internal/pkg/testenv/testenv_test.go
  internal/pkg/upgrade/node_test.go
  internal/pkg/util/util_test.go
  internal/pkg/warewulfd/provision_test.go
  internal/pkg/warewulfd/util_test.go
  overlays/NetworkManager/internal/networkmanager_test.go
  overlays/debian.interfaces/internal/debian_interfaces_test.go
  overlays/debug/internal/debug_test.go
  overlays/fstab/internal/fstab_test.go
  overlays/host/internal/host_test.go
  overlays/hostname/internal/hostname_test.go
  overlays/hosts/internal/hosts_test.go
  overlays/ifcfg/internal/ifcfg_test.go
  overlays/ignition/internal/ignition_test.go
  overlays/issue/internal/issue_test.go
  overlays/localtime/internal/localtime_test.go
  overlays/netplan/internal/netplan_test.go
  overlays/resolv/internal/resolv_test.go
  overlays/ssh.authorized_keys/internal/ssh_authorized_keys_test.go
  overlays/ssh.host_keys/internal/ssh_host_keys_test.go
  overlays/syncuser/internal/syncuser_test.go
  overlays/systemd.netname/internal/systemd_netname_test.go
  overlays/udev.netname/internal/udev_netname_test.go
  overlays/wicked/internal/wicked_test.go
  overlays/wwclient/internal/wwclient_test.go
  overlays/wwinit/internal/wwinit_test.go
Labels: testing

#1619 Fix a panic introduced by #1598
  internal/pkg/node/fields.go
Labels: bug, nochangelog

#1568 Introduce Resource concept
  CHANGELOG.md
  docs/man/man5/warewulf.conf.5
  etc/warewulf.conf
  go.mod
  internal/app/wwctl/node/add/main.go
  internal/app/wwctl/node/list/main_test.go
  internal/app/wwctl/node/set/main.go
  internal/app/wwctl/overlay/show/main_test.go
  internal/app/wwctl/profile/add/main.go
  internal/app/wwctl/profile/add/root.go
  internal/app/wwctl/profile/list/main_test.go
  internal/app/wwctl/profile/set/main.go
  internal/app/wwctl/upgrade/nodes/cobra.go
  internal/pkg/config/nfs.go
  internal/pkg/config/root_test.go
  internal/pkg/node/constructors_test.go
  internal/pkg/node/datastructure.go
  internal/pkg/node/fields_test.go
  internal/pkg/node/flags.go
  internal/pkg/node/mergo.go
  internal/pkg/node/mergo_test.go
  internal/pkg/node/methods.go
  internal/pkg/overlay/datastructure.go
  internal/pkg/overlay/funcmap.go
  internal/pkg/upgrade/config.go
  internal/pkg/upgrade/config_test.go
  internal/pkg/upgrade/node.go
  internal/pkg/upgrade/node_test.go
  overlays/fstab/internal/fstab_test.go
  overlays/fstab/internal/nodes.conf
  overlays/fstab/internal/warewulf.conf
  overlays/fstab/rootfs/etc/fstab.ww
  overlays/host/internal/warewulf.conf
  overlays/host/internal/warewulf.conf-static
  overlays/hosts/internal/warewulf.conf
  overlays/wwinit/internal/warewulf.conf
  overlays/wwinit/internal/wwinit_test.go
  userdocs/contents/configuration.rst
  userdocs/contents/nodeconfig.rst
  userdocs/contents/overlays.rst
  userdocs/contributing/development-environment-vagrant.rst
  userdocs/quickstart/debian12.rst
  userdocs/quickstart/el.rst
  userdocs/quickstart/suse15.rst
Labels: enhancement, nfs

#1632 Adjust umask during overlay build
  internal/app/wwctl/overlay/build/main.go
  internal/app/wwctl/server/root.go
Labels: bug, nochangelog

#1642 Fix a null-pointer bug in `wwctl upgrade config`
  internal/pkg/upgrade/config.go
  internal/pkg/upgrade/node.go
Labels: bug, nochangelog

#1643 Expand nodes when rendering overlay templates
  internal/pkg/node/methods.go
  internal/pkg/node/methods_test.go
  internal/pkg/overlay/datastructure.go
  internal/pkg/overlay/overlay_test.go
  overlays/debug/internal/debug_test.go
Labels: bug, nochangelog

#1645 Remove a vestigial printf from wwctl upgrade
  internal/pkg/upgrade/node.go
Labels: nochangelog, logging

#1644 Linting fixes called-out by vscode
  internal/pkg/node/fields_test.go
  internal/pkg/node/ignition.go
  internal/pkg/overlay/config.go
  internal/pkg/overlay/overlay.go
  internal/pkg/overlay/overlay_test.go
Labels: refactor

#1647 Enhancements for node.Field formatting
  internal/pkg/node/fields.go
  internal/pkg/node/fields_test.go
  internal/pkg/node/mergo_test.go
Labels: bug, nochangelog

#1648 Fix newline handling in /etc/issue
  CHANGELOG.md
  overlays/issue/internal/issue_test.go
  overlays/issue/internal/nodes.conf
  overlays/issue/rootfs/etc/issue.ww
Labels: bug, overlay

#1633 Refactor and fix wwctl <node|profile> edit
  internal/app/wwctl/image/delete/main.go
  internal/app/wwctl/node/delete/main.go
  internal/app/wwctl/node/edit/main.go
  internal/app/wwctl/node/imprt/main.go
  internal/app/wwctl/node/set/main.go
  internal/app/wwctl/profile/edit/main.go
  internal/app/wwctl/profile/set/main.go
  internal/pkg/api/node/hash.go
  internal/pkg/api/profile/delete.go
  internal/pkg/api/profile/edit.go
  internal/pkg/api/util/util.go
  internal/pkg/node/checkconf.go
  internal/pkg/node/constructors.go
  internal/pkg/node/modifiers.go
  internal/pkg/util/confirm.go
  internal/pkg/util/util.go
Labels: bug, refactor

#1649 Change image provision directory to "images"
  internal/app/wwctl/image/copy/main_test.go
  internal/app/wwctl/image/exec/main_test.go
  internal/pkg/image/config.go
Labels: nochangelog

#1656 Refactor kernel args as a slice
  CHANGELOG.md
  internal/app/wwctl/node/add/main_test.go
  internal/pkg/node/datastructure.go
  internal/pkg/node/fields_test.go
  internal/pkg/node/mergo_test.go
  internal/pkg/node/methods_test.go
  internal/pkg/overlay/overlay_test.go
  internal/pkg/upgrade/node.go
  internal/pkg/upgrade/node_test.go
  internal/pkg/warewulfd/provision.go
  overlays/debug/internal/nodes.conf
  overlays/debug/rootfs/tstruct.md.ww
  overlays/issue/internal/nodes.conf
  overlays/issue/rootfs/etc/issue.ww
Labels: enhancement

#1659 Added warewulfd:/overlay-file/{overlay}/{path...}?render={nodeID}
  CHANGELOG.md
  internal/pkg/testenv/testenv.go
  internal/pkg/warewulfd/overlay.go
  internal/pkg/warewulfd/overlay_test.go
  internal/pkg/warewulfd/warewulfd.go
Labels: enhancement

#1652 updated slack link
  userdocs/contributing/contributing.rst
Labels: documentation, nochangelog

#1670 Fix default nodes.conf to use the new kernel command line list format
  CHANGELOG.md
  etc/nodes.conf
Labels: bug
