Repository warewulf/warewulf, pull requests merged in 2025-03, with the labels that each got.

#1779 Better handling for missing NetDev.Device and clean-up dracut NetworkManager connections
  CHANGELOG.md
  overlays/NetworkManager/internal/networkmanager_test.go
  overlays/NetworkManager/rootfs/etc/NetworkManager/conf.d/ww4-unmanaged.ww
  overlays/NetworkManager/rootfs/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/NetworkManager/rootfs/warewulf/init.d/20-NetworkManager
  overlays/ifcfg/internal/ifcfg_test.go
  overlays/ifcfg/rootfs/etc/sysconfig/network-scripts/ifcfg.ww
Labels: overlay

#1770 Multiple dependabot changes
  .github/workflows/check.yml
  CHANGELOG.md
  LICENSE_DEPENDENCIES.md
  go.mod
  go.sum
Labels: dependencies

#1811 minor typo debian-quickstart.rst
  userdocs/getting-started/debian-quickstart.rst
Labels: typo, nochangelog

#1822 Adding New SOS Plugin
  CHANGELOG.md
  Makefile
  Variables.mk
  include/sos/warewulf.py
  userdocs/troubleshooting/troubleshooting.rst
  warewulf.spec.in
Labels: stake:ciq

#1818 Allow discover of nodes with network only in profile
  CHANGELOG.md
  internal/pkg/warewulfd/nodedb.go
  internal/pkg/warewulfd/nodedb_test.go
Labels: stake:ciq

#1803 fix Dockerfile: go1.22 is required for docker build
  Dockerfile
Labels: nochangelog

#1765 Add `--overwrite` to `wwctl overlay import`
  CHANGELOG.md
  internal/app/wwctl/overlay/imprt/main.go
  internal/app/wwctl/overlay/imprt/main_test.go
  internal/app/wwctl/overlay/imprt/root.go
  internal/pkg/util/copyfile.go
Labels: documentation, overlay

#1831 Various minor documentation updates
  userdocs/overlays/overlays.rst
  userdocs/server/bootloaders.rst
  userdocs/server/installation.rst
Labels: documentation, nochangelog

#1836 Fix yaml indentation in network bond example
  userdocs/nodes/network.rst
Labels: documentation, nochangelog
