Repository warewulf/warewulf, pull requests merged in 2025-04, with the labels that each got.

#1588 OpenAPI REST API
  CHANGELOG.md
  LICENSE_DEPENDENCIES.md
  Makefile
  etc/auth.conf
  go.mod
  go.sum
  internal/app/wwctl/node/list/main_test.go
  internal/app/wwctl/profile/list/main_test.go
  internal/app/wwctl/server/root.go
  internal/pkg/api/image/image.go
  internal/pkg/config/api.go
  internal/pkg/config/authentication.go
  internal/pkg/config/buildconfig.go.in
  internal/pkg/config/root.go
  internal/pkg/config/root_test.go
  internal/pkg/image/config.go
  internal/pkg/image/util.go
  internal/pkg/node/constructors.go
  internal/pkg/node/datastructure.go
  internal/pkg/node/methods.go
  internal/pkg/node/queries.go
  internal/pkg/node/queries_test.go
  internal/pkg/warewulfd/api/api.go
  internal/pkg/warewulfd/api/authentication.go
  internal/pkg/warewulfd/api/image.go
  internal/pkg/warewulfd/api/image_test.go
  internal/pkg/warewulfd/api/node.go
  internal/pkg/warewulfd/api/node_test.go
  internal/pkg/warewulfd/api/overlay.go
  internal/pkg/warewulfd/api/overlay_test.go
  internal/pkg/warewulfd/api/profile.go
  internal/pkg/warewulfd/api/profile_test.go
  internal/pkg/warewulfd/daemon.go
  internal/pkg/warewulfd/nodedb.go
  internal/pkg/warewulfd/server/server.go
  internal/pkg/warewulfd/warewulfd.go
  userdocs/images/images.rst
  userdocs/index.rst
  userdocs/overlays/overlays.rst
  userdocs/server/api.rst
  userdocs/server/configuration.rst
  warewulf.spec.in
Labels: stake:ciq

#1850 Make nm-wait-online-initrd.service wait for interfaces to be online during dracut boot
  CHANGELOG.md
  Makefile
  dracut/modules.d/90wwinit/module-setup.sh
  dracut/modules.d/90wwinit/nm-wait-online-initrd.service.override
Labels: needs confirmation

#1867 Remove accidental init.bak
  init.bak
Labels: nochangelog
