Repository warewulf/warewulf, pull requests merged in 2025-02, with the labels that each got.

#1681 Document commas in kernel arguments
  CHANGELOG.md
  userdocs/contents/nodeconfig.rst
Labels: documentation

#1694 Remove a redundant "Building image" log message after image exec
  CHANGELOG.md
  internal/app/wwctl/image/exec/main.go
Labels: logging

#1693 Recommend installing ipmitool with Warewulf package
  CHANGELOG.md
  warewulf.spec.in
Labels: build

#1686 Document setting the wwclient port
  userdocs/contents/configuration.rst
Labels: documentation, nochangelog

#1696 Simplify Makefile and spec
  .gitattributes
  CHANGELOG.md
  Makefile
  warewulf.spec.in
Labels: build

#1711 Prevent merging of zero-value net.IP fields
  CHANGELOG.md
  internal/pkg/node/mergo.go
  internal/pkg/node/mergo_test.go
Labels: node

#1706 Only calculate image chroot size when requested
  CHANGELOG.md
  internal/app/wwctl/image/list/main.go
  internal/app/wwctl/image/list/main_test.go
  internal/pkg/api/image/image.go
  internal/pkg/api/routes/v1/routes.proto
  internal/pkg/api/routes/wwapiv1/routes.pb.go
Labels: container

#1707 Remove `warewulf.conf:syslog`
  CHANGELOG.md
  docs/man/man5/warewulf.conf.5
  etc/warewulf.conf
  include/systemd/warewulfd.service.in
  internal/app/wwctl/overlay/show/main_test.go
  internal/pkg/config/buildconfig.go.in
  internal/pkg/config/root_test.go
  internal/pkg/upgrade/config.go
  internal/pkg/upgrade/config_test.go
  internal/pkg/warewulfd/daemon.go
  overlays/debug/internal/debug_test.go
  overlays/debug/rootfs/tstruct.md.ww
  overlays/fstab/internal/warewulf.conf
  overlays/host/internal/warewulf.conf
  overlays/host/internal/warewulf.conf-static
  overlays/hosts/internal/warewulf.conf
  overlays/wwinit/internal/warewulf.conf
  overlays/wwinit/internal/wwinit_test.go
  userdocs/contents/configuration.rst
  userdocs/contents/troubleshooting.rst
  userdocs/contributing/development-environment-vagrant.rst
  userdocs/quickstart/debian12.rst
  userdocs/quickstart/el.rst
  userdocs/quickstart/suse15.rst
Labels: config, simplification

#1709 Document `warewulf.conf:dhcp.template`
  CHANGELOG.md
  userdocs/contents/configuration.rst
Labels: documentation

#1657 Run staticcheck as part of GitHub CI
  .github/workflows/check.yml
  CHANGELOG.md
  Makefile
  Tools.mk
  internal/app/wwctl/image/exec/child/main.go
  internal/app/wwctl/image/exec/main.go
  internal/pkg/api/image/image.go
  internal/pkg/api/node/add.go
  internal/pkg/api/profile/add.go
  internal/pkg/api/routes/wwapiv1/routes.pb.go
  internal/pkg/api/routes/wwapiv1/routes.pb.gw.go
  internal/pkg/api/routes/wwapiv1/routes_grpc.pb.go
  internal/pkg/config/buildconfig.go.in
  internal/pkg/config/dhcp.go
  internal/pkg/config/mounts.go
  internal/pkg/config/nfs.go
  internal/pkg/image/build.go
  internal/pkg/image/initramfs.go
  internal/pkg/kernel/kernel.go
  internal/pkg/kernel/kernel_test.go
  internal/pkg/upgrade/config.go
  internal/pkg/upgrade/node.go
  internal/pkg/util/util.go
Labels: testing

#1730 Update overlay flags for clarity
  CHANGELOG.md
  internal/app/wwctl/flags/flags.go
  internal/app/wwctl/node/add/root.go
  internal/app/wwctl/node/set/root.go
  internal/app/wwctl/profile/add/root.go
  internal/app/wwctl/profile/set/root.go
  internal/pkg/node/datastructure.go
  userdocs/contents/overlays.rst
Labels: overlay, node

#1738 Fix image completion
  internal/app/wwctl/completions/completions.go
  internal/app/wwctl/node/add/root.go
  internal/app/wwctl/node/set/root.go
  internal/app/wwctl/profile/add/root.go
  internal/app/wwctl/profile/set/root.go
Labels: image, nochangelog

#1736 syncuser improvements
  CHANGELOG.md
  etc/nodes.conf
  internal/app/wwctl/image/build/main.go
  internal/app/wwctl/image/build/root.go
  internal/app/wwctl/image/exec/main.go
  internal/app/wwctl/image/syncuser/main.go
  internal/app/wwctl/image/syncuser/root.go
  internal/pkg/api/image/image.go
  internal/pkg/image/syncuser.go
  internal/pkg/overlay/funcmap.go
  internal/pkg/overlay/funcmap_test.go
  internal/pkg/overlay/overlay.go
  overlays/syncuser/internal/nodes.conf
  overlays/syncuser/internal/syncuser_test.go
  overlays/syncuser/rootfs/etc/group.ww
  overlays/syncuser/rootfs/etc/passwd.ww
  userdocs/contents/images.rst
  userdocs/contents/ipmi.rst
  userdocs/contents/nodeconfig.rst
  userdocs/contents/overlays.rst
  userdocs/contents/setup.rst
  userdocs/contents/templating.rst
Labels: overlay, image

#1739 Added support for a DNSSEARCH netdev tag in network configuration overlays
  CHANGELOG.md
  overlays/NetworkManager/internal/networkmanager_test.go
  overlays/NetworkManager/internal/nodes.conf
  overlays/NetworkManager/internal/nodes.conf-vlan
  overlays/NetworkManager/internal/nodes_empty_mac.conf
  overlays/NetworkManager/rootfs/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/ifcfg/internal/ifcfg_test.go
  overlays/ifcfg/internal/nodes.conf
  overlays/ifcfg/internal/nodes.conf-vlan
  overlays/ifcfg/rootfs/etc/sysconfig/network-scripts/ifcfg.ww
  overlays/resolv/internal/nodes.conf
  overlays/resolv/internal/resolv_test.go
  overlays/resolv/rootfs/etc/resolv.conf.ww
  userdocs/contents/overlays.rst
Labels: overlay

#1732 Update PS1 during `wwctl image shell` to include working directory
  CHANGELOG.md
  internal/app/wwctl/image/exec/child/main.go
  userdocs/contents/images.rst
Labels: image

#1740 create commandline options for Makefile
  CHANGELOG.md
  Makefile
  userdocs/quickstart/el.rst
  warewulf.spec.in
Labels: documentation

#1746 Default nfs resources
  CHANGELOG.md
  etc/nodes.conf
  internal/pkg/upgrade/node.go
  internal/pkg/upgrade/node_test.go
Labels: nfs

#1745 Don't use DHCP for interfaces attached to a bond
  CHANGELOG.md
  overlays/NetworkManager/internal/networkmanager_test.go
  overlays/NetworkManager/rootfs/etc/NetworkManager/system-connections/ww4-managed.ww
  overlays/ifcfg/internal/ifcfg_test.go
Labels: overlay

#1764 Reduced default verbosity of `wwctl overlay build`
  CHANGELOG.md
  internal/pkg/overlay/overlay.go
Labels: logging

#1775 Install git before checkout
  .github/workflows/nightly-release.yml
  CHANGELOG.md
Labels: build
