Repository warewulf/warewulf, pull requests merged in 2025-05, with the labels that each got.

#1874 Fix typo in rpm github action
  .github/actions/rpm/action.yml
Labels: build, stake:ciq

#1884 Updated udev overlay for case-insensitive
  CHANGELOG.md
  CONTRIBUTORS.md
  overlays/udev.netname/rootfs/etc/udev/rules.d/70-persistent-net.rules.ww
Labels: stake:ciq

#1905 Address unhandled deadcode issues
  Makefile
  go.mod
  go.sum
  internal/pkg/api/image/image.go
Labels: nochangelog

#1914 Misc. documentation typo fixes
  userdocs/overlays/overlays.rst
  userdocs/release/v4.6.0.rst
Labels: documentation, nochangelog
